// <auto-generated />
using BehaviourAnalysis.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BehaviourAnalysis.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210512074518_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BehaviourAnalysis.Domain.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("QuestionId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("BehaviourAnalysis.Domain.Models.Questionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Angry")
                        .HasColumnType("int");

                    b.Property<int>("AvoidingPeople")
                        .HasColumnType("int");

                    b.Property<int>("BlamingYourself")
                        .HasColumnType("int");

                    b.Property<int>("BreathingRapidly")
                        .HasColumnType("int");

                    b.Property<int>("ChangesInEating")
                        .HasColumnType("int");

                    b.Property<int>("CloseFriend")
                        .HasColumnType("int");

                    b.Property<int>("Hopeless")
                        .HasColumnType("int");

                    b.Property<int>("MaterialPossession")
                        .HasColumnType("int");

                    b.Property<int>("NegativeThoughts")
                        .HasColumnType("int");

                    b.Property<int>("Nervous")
                        .HasColumnType("int");

                    b.Property<int>("Nightmares")
                        .HasColumnType("int");

                    b.Property<int>("OverReacting")
                        .HasColumnType("int");

                    b.Property<int>("Panic")
                        .HasColumnType("int");

                    b.Property<int>("Shy")
                        .HasColumnType("int");

                    b.Property<int>("SocialMediaAddiction")
                        .HasColumnType("int");

                    b.Property<int>("StressfulMemories")
                        .HasColumnType("int");

                    b.Property<int>("SuicidalThoughts")
                        .HasColumnType("int");

                    b.Property<int>("Sweating")
                        .HasColumnType("int");

                    b.Property<int>("Tired")
                        .HasColumnType("int");

                    b.Property<int>("TroublesInConcentration")
                        .HasColumnType("int");

                    b.Property<int>("TroublesInFocusing")
                        .HasColumnType("int");

                    b.Property<int>("TroublesInSleeping")
                        .HasColumnType("int");

                    b.Property<int>("TroublesWithWork")
                        .HasColumnType("int");

                    b.Property<int>("WeightGain")
                        .HasColumnType("int");

                    b.HasKey("QuestionnaireId");

                    b.ToTable("Questionnaire");
                });
#pragma warning restore 612, 618
        }
    }
}
