// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BehaviourAnalysis.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BehaviourAnalysis.Domain.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("QuestionId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("BehaviourAnalysis.Domain.Questionnaire", b =>
                {
                    b.Property<int>("QuestionnaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Angry")
                        .HasColumnType("bit");

                    b.Property<bool>("AvoidingPeople")
                        .HasColumnType("bit");

                    b.Property<bool>("BlamingYourself")
                        .HasColumnType("bit");

                    b.Property<bool>("BreathingRapidly")
                        .HasColumnType("bit");

                    b.Property<bool>("ChangesInEating")
                        .HasColumnType("bit");

                    b.Property<bool>("CloseFriend")
                        .HasColumnType("bit");

                    b.Property<bool>("Hopeless")
                        .HasColumnType("bit");

                    b.Property<bool>("MaterialPossession")
                        .HasColumnType("bit");

                    b.Property<bool>("NegativeThoughts")
                        .HasColumnType("bit");

                    b.Property<bool>("Nervous")
                        .HasColumnType("bit");

                    b.Property<bool>("Nightmares")
                        .HasColumnType("bit");

                    b.Property<bool>("OverReacting")
                        .HasColumnType("bit");

                    b.Property<bool>("Panic")
                        .HasColumnType("bit");

                    b.Property<bool>("Shy")
                        .HasColumnType("bit");

                    b.Property<bool>("SocialMediaAddiction")
                        .HasColumnType("bit");

                    b.Property<bool>("StressfulMemories")
                        .HasColumnType("bit");

                    b.Property<bool>("SuicidalThoughts")
                        .HasColumnType("bit");

                    b.Property<bool>("Sweating")
                        .HasColumnType("bit");

                    b.Property<bool>("Tired")
                        .HasColumnType("bit");

                    b.Property<bool>("TroublesInConcentration")
                        .HasColumnType("bit");

                    b.Property<bool>("TroublesInFocusing")
                        .HasColumnType("bit");

                    b.Property<bool>("TroublesInSleeping")
                        .HasColumnType("bit");

                    b.Property<bool>("TroublesWithWork")
                        .HasColumnType("bit");

                    b.Property<bool>("WeightGain")
                        .HasColumnType("bit");

                    b.HasKey("QuestionnaireId");

                    b.ToTable("Questionnaire");
                });
#pragma warning restore 612, 618
        }
    }
}
