INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling nervous all the time')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having sudden panic attacks')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you breathing rapidly')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you sweating excessively')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having troubles in concentration')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having troubles in sleeping')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having troubles with work')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling hopeless')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling angry')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Do you feel like over reacting')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling any changes in eating habits')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having any suicidal thoughts')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling tired all the time')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Do you have a close friend that you can share your feelings')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you addicted to the social media platforms (Facebook, Instagram, Twitter etc.)')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Do you feel like rapid weight gain')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Do you feel like obsessed with material possession')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling shy')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you experiencing any emotional flashbacks of stressful memories')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having nightmares')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Do you feel like avoiding people or activities')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you feeling negative')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you having troubles in focusing')
INSERT INTO [dbo].[Question] ([QuestionBody]) VALUES ('Are you blaming yourself')
GO